{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "digdag.fullname" . }}
  {{- if .Values.metrics.prometheusRule.namespace }}
  namespace: {{ .Values.metrics.prometheusRule.namespace }}
  {{- end }}
  labels:
    {{- include "digdag.labels" . | nindent 4 }}
spec:
  groups:
  {{- with .Values.metrics.prometheusRule.rules }}
    - name: {{ template "digdag.name" $ }}
      rules: {{- tpl . | nindent 8 }}
  {{- end }}
{{- end }}
