apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "digdag.fullname" . }}
  labels:
    {{- include "digdag.labels" . | nindent 4 }}
data:
  server.properties: |-
{{ tpl .Values.configuration . | indent 4 }}
