apiVersion: v2
name: digdag
description: A Helm chart for Digdag
type: application
version: 0.5.1
appVersion: 0.10.0
dependencies:
  - condition: postgresql-ha.enabled
    name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: 6.5.x
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 10.2.x
engine: gotpl
home: https://github.com/skyoo2003/helm-charts/tree/main/charts/digdag
icon: https://docs.digdag.io/_static/logo/logo-digdag-sq-tr.png
keywords:
  - digdag
  - workflow
maintainers:
  - name: skyoo2003
    email: skyoo2003@gmail.com
annotations:
  category: Workflow
  # https://artifacthub.io/docs/topics/annotations/helm/
  artifacthub.io/changes: |
    - Change prometheus jmx exporter image
    - Fix job-migrator error
    - Restore digdag replicaCount
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: digdag
      image: ghcr.io/skyoo2003/digdag:0.0.1
    - name: wait-for-it
      image: willwill/wait-for-it:latest
    - name: prometheus-jmx-exporter
      image: ghcr.io/skyoo2003/prometheus-jmx-exporter:0.0.1
  artifacthub.io/license: MIT
